version: "3.9"
services:
  cospend:
    environment:
      - GORM_CONNECTION=${GORM_CONNECTION}
      - HTTP_PORT=${HTTP_PORT}
      - JWT_EXPIRED=${JWT_EXPIRED}
      - LOG_FORMAT=${LOG_FORMAT}
      - LOG_LEVEL=${LOG_LEVEL}
      - SECRET_KEY=${SECRET_KEY}
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - cospend

  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - cospend

volumes:
  pg_data:

    # Networks to be created to facilitate communication between containers
networks:
  cospend:
    driver: bridge
